# Generated by Django 3.1 on 2020-08-20 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='host',
            new_name='hostId',
        ),
    ]
