# Generated by Django 3.1 on 2020-08-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0006_auto_20200822_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(choices=[('', '인원 선택'), (3, '3 명'), (4, '4 명'), (5, '5 명')]),
        ),
    ]
