# Generated by Django 3.1 on 2020-08-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_auto_20200822_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='hostId',
        ),
        migrations.AddField(
            model_name='roomplayer',
            name='type',
            field=models.CharField(choices=[('H', 'Host'), ('P', 'Player'), ('O', 'Observer')], default='H', max_length=1),
            preserve_default=False,
        ),
    ]
