# Generated by Django 3.1 on 2020-08-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_auto_20200823_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('roomId', models.IntegerField()),
                ('userId', models.IntegerField()),
                ('type', models.CharField(choices=[('H', 'Host'), ('P', 'Player'), ('O', 'Observer')], max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='RoomPlayer',
        ),
    ]
