# Generated by Django 3.1 on 2020-08-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_auto_20200823_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomuser',
            name='type',
        ),
        migrations.AddField(
            model_name='room',
            name='hostId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomuser',
            name='seat',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
