# Generated by Django 3.1 on 2020-08-30 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0013_auto_20200830_0250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomuser',
            old_name='roomId',
            new_name='room',
        ),
        migrations.RenameField(
            model_name='roomuser',
            old_name='userId',
            new_name='user',
        ),
    ]
