# Generated by Django 3.1 on 2020-08-30 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('room', '0014_auto_20200830_0351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='hostId',
            new_name='host',
        ),
        migrations.RemoveField(
            model_name='room',
            name='gameId',
        ),
        migrations.AddField(
            model_name='room',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.game'),
        ),
    ]
