# Generated by Django 3.1 on 2020-09-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0015_auto_20200830_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomuser',
            name='seat',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
