# Generated by Django 3.1 on 2020-09-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0016_auto_20200901_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomuser',
            name='seat',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
    ]
