# Generated by Django 3.1 on 2020-08-29 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('playerNum', models.IntegerField(choices=[(3, 3), (4, 4), (5, 5)])),
                ('mode', models.CharField(choices=[('', '모드 선택'), ('O', 'Original'), ('C', 'Casual')], max_length=1)),
                ('stage', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('P', 'Playing'), ('E', 'End')], default='P', max_length=1)),
            ],
        ),
    ]
