# Generated by Django 3.1 on 2020-08-22 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
